<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- can be changed to <TargetFrameworks>net8.0;net9.0;...</> if necessary, but then we need to specify `-f net8.0` when calling dotnet run, which would be annoying -->
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>interface_tests</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
      <Compile Include="../../dll-bindings/asar.cs" Link="asar.cs" />
  </ItemGroup>

</Project>
