Asar is licensed under GNU Lesser General Public License, version 3 or later. The full legal text
  can be found in license-lgpl.txt, but it is also allowed to obey the following rules instead if
  you prefer that (legalese is complicated):

If you don't want to redistribute it or distribute modifications (aka you only want it for personal
  use), you may do whatever you want with it. The author of Asar claims no copyright over input,
  binary output or textual output (including error messages) generated by Asar.

If you do want to redistribute it, you must obey the LGPL. This means the following:
- You must credit the author. Don't claim it as your own. You may modify it and take credit for your
  modifications, but the author (Alcaro) must be credited for the original software.
- You must make it possible to replace your copy of Asar with another version, if anyone wants that.
  If you're using one of the dynamic libraries, you must either keep it as a separate file and allow
  anyone who wants to replace it, or you must offer all source codes and related files that are
  required to rebuild your tool to anyone who asks. If Asar is linked statically into the same
  program, only the latter option is possible.
- If you modify this software, it must clearly be labeled as a modification, and you must provide
  full source code to anyone who asks.

However, as a special exception, the DLL interface files (dll/asardll.h and dll/asardll.cpp)
are licensed under the WTFPL (version 2 or later), which much means you may use them for
anything you want. You don't need to make them upgradable, you don't need to credit the
author, and you don't need to release any source codes. Note that this does not apply to the DLLs
themselves, or anything compiled into a library.