<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>interface_tests</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
      <Compile Include="../../asar-dll-bindings/c_sharp/asar.cs" Link="asar.cs" />
  </ItemGroup>

</Project>
