// note for asar devs: autogenerated by update_c_bind.py, don't edit this
// directly! edit either asardll.h.in or interface-lib.cpp.
#ifndef ASAR_DLL_H_INCLUDED
#	define ASAR_DLL_H_INCLUDED

#define expectedapiversion 400

#include <stdbool.h>
#include <stddef.h> // for size_t

// These structures are returned from various functions
struct stackentry {
	const char * fullpath;
	const char * prettypath;
	int lineno;
	const char * details;
};

struct errordata {
	const char * fullerrdata;
	const char * rawerrdata;
	const char * block;
	const char * filename;
	int line;
	const struct stackentry * callstack;
	int callstacksize;
	const char * errname;
};

struct labeldata {
	const char * name;
	int location;
};

struct definedata {
	const char * name;
	const char * contents;
};

struct warnsetting {
	const char * warnid;
	bool enabled;
};

struct memoryfile {
	const char* path;
	const void* buffer;
	size_t length;
};

enum mappertype {
	invalid_mapper,
	lorom,
	hirom,
	sa1rom,
	bigsa1rom,
	sfxrom,
	exlorom,
	exhirom,
	norom
};

struct writtenblockdata {
	int pcoffset;
	int snesoffset;
	int numbytes;
};

struct patchparams {
	// The size of this struct. Set to (int)sizeof(patchparams).
	int structsize;

	// Filename of the patch to apply. (This is a path so that Asar
	// knows where to look for incsrc'd stuff. If you wish to apply a
	// patch that doesn't exist on the filesystem, use a memory file.)
	// Note that this (and all other filenames in this API) is always
	// UTF-8 encoded, even on windows.
	const char * patchloc;
	// Pointer to the ROM data to apply the patch to. This, along with
	// buflen and romlen, are assumed to be unheadered.
	char * romdata;
	// Length of the buffer pointed to by romdata.
	int buflen;
	// Size of the rom (passed as a pointer so asar can change it). This
	// may be changed by asar, but will never go above buflen; if you
	// try to expand the rom too much, you get a buffer_too_small error.
	// Pass a buffer with size = asar_maxromsize() to avoid this.
	// Note that the bytes of romdata at indices between romlen and
	// buflen do not need to be initialized.
	int * romlen;

	// Include paths to use when searching files.
	// Each string in includepaths is an include search path; see the
	// "Includes" chapter of the manual for details.
	const char** includepaths;
	int numincludepaths;

	// A list of additional defines to make available to the patch.
	const struct definedata* additional_defines;
	int additional_define_count;

	// Path to a text file to parse standard include search paths from.
	// Set to NULL to not use any standard includes search paths.
	const char* stdincludesfile;

	// Path to a text file to parse standard defines from.
	// Set to NULL to not use any standard defines.
	const char* stddefinesfile;

	// A list of warnings to enable or disable.
	// Specify warnings in the format "WXXXX" where XXXX = warning ID.
	const struct warnsetting * warning_settings;
	int warning_setting_count;

	// List of memory files to create on the virtual filesystem.
	const struct memoryfile * memory_files;
	int memory_file_count;

	// Set override_checksum_gen to true and generate_checksum to true/false
	// to force generating/not generating a checksum.
	bool override_checksum_gen;
	bool generate_checksum;

	// Set this to true for generated error and warning texts to always
	// contain their full call stack.
	bool full_call_stack;
};

#ifdef __cplusplus
extern "C" {
#endif

//Initializes Asar. Call this before doing anything.
//If it returns false, something went wrong, and you may not use any other Asar functions. This is
//either due to not finding the library, or not finding all expected functions in the library.
bool asar_init(void);

// Same as above, but instead of automatically looking for and trying to load asar.dll, takes
// a path to the Asar DLL and tries to load it.
// The path is expected to be UTF-8-encoded, even on Windows.
bool asar_init_with_dll_path(const char * dllpath);

//Frees all of Asar's structures and unloads the module. Only asar_init may be called after calling
// this; anything else will lead to segfaults.
void asar_close(void);

/* Returns the version, in the format major*10000+minor*100+bugfix*1. This
 * means that 1.2.34 would be returned as 10234.
 */
extern int (*asar_version)(void);

/* Returns the API version, format major*100+minor. Minor is incremented on
 * backwards compatible changes; major is incremented on incompatible changes.
 * Does not have any correlation with the Asar version.
 *
 * It's not very useful directly, since asar_init() verifies this automatically.
 * Calling this one also sets a flag that makes asar_init not instantly return
 * false; this is so programs expecting an older API won't do anything unexpected.
 */
extern int (*asar_apiversion)(void);

/* Clears out all errors, warnings and printed statements, and clears the file
 * cache. Not really useful, since asar_patch() already does this.
 */
extern bool (*asar_reset)(void);

/* Applies a patch.
 * See the documentation of struct patchparams for more information.
 * The return value is whether any errors appeared (false=errors, call
 * asar_geterrors for details). If there is an error, the romdata and
 * romlen passed in the patchparams will be left unchanged.
 */
extern bool (*asar_patch)(const struct patchparams *params);

/* Returns the maximum possible size of the output ROM from asar_patch().
 * Giving this size to buflen guarantees you will not get any buffer too small
 * errors; however, it is safe to give smaller buffers if you don't expect any
 * ROMs larger than 4MB or something.
 */
extern int (*asar_maxromsize)(void);

/* Get a list of all errors.
 * All pointers from these functions are valid only until the same function is
 * called again, or until asar_patch, asar_reset or asar_close is called,
 * whichever comes first. Copy the contents if you need it for a longer time.
 */
extern const struct errordata * (*asar_geterrors)(int * count);

/* Get a list of all warnings.
 */
extern const struct errordata * (*asar_getwarnings)(int * count);

/* Get a list of all printed data.
 */
extern const char * const * (*asar_getprints)(int * count);

/* Get a list of all labels.
 */
extern const struct labeldata * (*asar_getalllabels)(int * count);

/* Get the ROM location of one label. -1 means "not found".
 */
extern int (*asar_getlabelval)(const char * name);

/* Get the value of a define.
 */
extern const char * (*asar_getdefine)(const char * name);

/* Parses all defines in the parameter.
 * If there were any errors, returns an empty string.
 */
extern const char * (*asar_resolvedefines)(const char * data);

/* Gets the values and names of all defines.
 */
extern const struct definedata * (*asar_getalldefines)(int * count);

/* Parses a string containing math. It automatically assumes global scope (no
 * namespaces), and has access to all functions and labels from the last call
 * to asar_patch. Remember to check error to see if it's successful (NULL) or
 * if it failed (non-NULL, contains a descriptive string). It does not affect
 * asar_geterrors.
 */
extern double (*asar_math)(const char * math_, const char ** error);

/* Get a list of all the blocks written to the ROM by calls such as
 * asar_patch().
 */
extern const struct writtenblockdata * (*asar_getwrittenblocks)(int * count);

/* Get the mapper currently used by Asar.
 */
extern enum mappertype (*asar_getmapper)(void);

/* Generates the contents of a symbols file for in a specific format.
 * See the documentation of --symbols in the "Usage" chapter in the
 * manual for valid values of `type`.
 * Note that some formats include a crc checksum of the ROM. When using
 * this function, this will be the checksum of the unheadered ROM;
 * you'll need to fix that manually if the original ROM file was
 * actually headered.
 */
extern const char * (*asar_getsymbolsfile)(const char* type);

#ifdef __cplusplus
	}
#endif

#endif		// ASAR_DLL_H_INCLUDED
