#pragma once

#if defined(__clang__) || defined(__GNUC__)
[[gnu::format(printf, 2, 4)]]
#else
// msvc only has format string checking in enterprise edition lmao
// ehh who tf even develops on windows anyways
#endif
void error_impl(const char* error_id, const char* fmt_string, int whichpass, ...);

struct errfatal {};
struct errline : public errfatal {};
struct errblock : public errline {};
struct errnull : public errblock {};

#ifdef __clang__
// okay so this ## thing isn't very nice of me, but it works on all compilers
// for now. good enough until we upgrade to c++20 (and can use __VA_OPT__)
#pragma clang diagnostic ignored "-Wgnu-zero-variadic-macro-arguments"
#endif
#define throw_err_null(whichpass, id, ...) id(whichpass, ## __VA_ARGS__)
#define throw_err_block(whichpass, id, ...) (id(whichpass, ## __VA_ARGS__), throw errblock{})
#define throw_err_line(whichpass, id, ...) (id(whichpass, ## __VA_ARGS__), throw errline{})
#define throw_err_fatal(whichpass, id, ...) (id(whichpass, ## __VA_ARGS__), throw errfatal{})

#define ERR(id, fmt_string) template<typename... Ts> inline void id(int whichpass, Ts... args) { error_impl(#id, fmt_string, whichpass, args...); }

ERR(err_limit_reached, "Over %d errors detected. Aborting.")
ERR(err_werror, "One or more warnings was detected with werror on.")
ERR(err_buffer_too_small, "The given buffer is too small to contain the resulting ROM.")
ERR(err_params_null, "params passed to asar_patch_ex() is null.")
ERR(err_params_invalid_size, "Size of params passed to asar_patch_ex() is invalid.")
ERR(err_cmdl_define_invalid, "Invalid define name in %s: '%s'.")
ERR(err_cmdl_define_override, "%s '%s' overrides a previous define. Did you specify the same define twice?")
ERR(err_create_rom_failed, "Couldn't create ROM.")
ERR(err_open_rom_failed, "Couldn't open ROM.")
ERR(err_open_rom_not_smw_extension, "Doesn't look like an SMW ROM. (Maybe its extension is wrong?)")
ERR(err_open_rom_not_smw_header, "Doesn't look like an SMW ROM. (Maybe it's headered?)")
ERR(err_stddefines_no_identifier, "stddefines.txt contains a line with a value, but no identifier.")
ERR(err_stddefine_after_closing_quote, "Broken std defines. (Something after closing quote)")
ERR(err_failed_to_open_file, "Failed to open file '%s'.")
ERR(err_file_not_found, "File '%s' wasn't found.")
ERR(err_file_offset_out_of_bounds, "File offset %s out of bounds for file '%s'.")
ERR(err_mismatched_parentheses, "Mismatched parentheses.")
ERR(err_invalid_hex_value, "Invalid hex value.")
ERR(err_invalid_binary_value, "Invalid binary value.")
ERR(err_invalid_character, "Invalid character.")
//ERR(err_string_literal_not_terminated, "String literal not terminated.")
//ERR(err_malformed_function_call, "Malformed function call.")
ERR(err_invalid_number, "Invalid number.")
ERR(err_garbage_near_quoted_string, "Garbage near quoted string.")
ERR(err_mismatched_quotes, "Mismatched quotes.")
ERR(err_rom_too_short, "ROM is too short to have a title. (Expected '%s')")
ERR(err_rom_title_incorrect, "ROM title is incorrect. Expected '%s', got '%s'.")
ERR(err_bank_border_crossed, "A bank border was crossed, SNES address $%06X.")
ERR(err_start_of_file, "This command may only be used at the start of a file.")
ERR(err_invalid_version_number, "Invalid version number.")
ERR(err_asar_too_old, "This version of Asar is too old for this patch.")
ERR(err_relative_branch_out_of_bounds, "Relative branch out of bounds. (Distance is %s).")
ERR(err_snes_address_doesnt_map_to_rom, "SNES address %s doesn't map to ROM.")
ERR(err_snes_address_out_of_bounds, "SNES address %s out of bounds.")
ERR(err_invalid_tcall, "Invalid tcall.")
ERR(err_use_xplus, "Use (x+) instead.")
ERR(err_opcode_length_too_long, "Opcode length is too long.")
ERR(err_superfx_invalid_short_address, "Invalid short address parameter: $%s. (Must be even number and $0000-$01FE)")
ERR(err_superfx_invalid_register, "Invalid register for opcode; valid range is %d-%d.")
ERR(err_invalid_opcode_length, "Invalid opcode length specification.")
ERR(err_invalid_mapper, "Invalid mapper.")
ERR(err_nan, "NaN encountered.")
ERR(err_division_by_zero, "Division by zero.")
//ERR(err_modulo_by_zero, "Modulo by zero.")
ERR(err_unknown_operator, "Unknown operator.")
ERR(err_invalid_input, "Invalid input.")
ERR(err_invalid_function_name, "Invalid function name.")
ERR(err_function_not_found, "Function '%s' wasn't found.")
ERR(err_function_redefined, "Function '%s' redefined.")
ERR(err_broken_function_declaration, "Broken function declaration.")
//ERR(err_wrong_num_parameters, "Wrong number of parameters to function.")
ERR(err_invalid_param_name, "Invalid parameter name '%s'.")
ERR(err_invalid_label_name, "Invalid label name.")
ERR(err_label_not_found, "Label '%s' wasn't found.")
ERR(err_label_redefined, "Label '%s' redefined.")
ERR(err_broken_label_definition, "Broken label definition.")
ERR(err_macro_label_outside_of_macro, "Macro label outside of a macro.")
ERR(err_invalid_namespace_name, "Invalid namespace name.")
ERR(err_invalid_namespace_use, "Invalid use of namespace command.")
ERR(err_invalid_struct_name, "Invalid struct name.")
ERR(err_struct_not_found, "Struct '%s' wasn't found.")
ERR(err_struct_redefined, "Struct '%s' redefined.")
ERR(err_struct_invalid_parent_name, "Invalid parent name.")
ERR(err_invalid_label_missing_closer, "Invalid label name, missing array closer.")
//ERR(err_invalid_subscript, "Invalid array subscript after first scope resolution.")
ERR(err_label_missing_parent, "This label has no parent.")
ERR(err_struct_without_endstruct, "struct without matching endstruct.")
ERR(err_nested_struct, "Can not nest structs.")
ERR(err_missing_struct_params, "Missing struct parameters.")
ERR(err_too_many_struct_params, "Too many struct parameters.")
ERR(err_missing_extends, "Missing extends keyword.")
ERR(err_invalid_endstruct_count, "Invalid endstruct parameter count.")
ERR(err_expected_align, "Expected align parameter.")
ERR(err_endstruct_without_struct, "endstruct can only be used in combination with struct.")
ERR(err_alignment_too_small, "Alignment must be >= 1.")
ERR(err_invalid_define_name, "Invalid define name.")
ERR(err_define_not_found, "Define '%s' wasn't found.")
ERR(err_define_not_found2, "Define '%s' wasn't found.")
ERR(err_broken_define_declaration, "Broken define declaration.")
ERR(err_overriding_builtin_define, "Trying to set define '%s', which is the name of a built-in define and thus can't be modified.")
//ERR(err_define_label_math, "!Define #= Label is not allowed with non-static labels.")
ERR(err_mismatched_braces, "Mismatched braces.")
ERR(err_invalid_macro_name, "Invalid macro name.")
ERR(err_macro_not_found, "Macro '%s' wasn't found.")
ERR(err_macro_redefined, "Macro '%s' redefined. First defined at: %s:%d")
ERR(err_broken_macro_declaration, "Broken macro declaration.")
ERR(err_invalid_macro_param_name, "Invalid macro parameter name.")
ERR(err_macro_param_not_found, "Macro parameter '%s' wasn't found.%s")
ERR(err_macro_param_redefined, "Macro parameter '%s' redefined")
ERR(err_broken_macro_usage, "Broken macro usage.")
ERR(err_macro_wrong_num_params, "Wrong number of parameters to macro.")
ERR(err_misplaced_endmacro, "Misplaced endmacro.")
ERR(err_unclosed_macro, "Unclosed macro: '%s'.")
//ERR(err_label_in_conditional, "Non-static label in %s command.")
ERR(err_misplaced_elseif, "Misplaced elseif.")
ERR(err_elseif_in_while, "Can't use elseif in a while loop.")
ERR(err_misplaced_endif, "Misplaced endif.")
ERR(err_misplaced_else, "Misplaced else.")
ERR(err_else_in_while_loop, "Can't use else in a while loop.")
ERR(err_unclosed_if, "Unclosed if statement.")
ERR(err_unknown_command, "Unknown command.")
ERR(err_broken_incbin, "Broken incbin command.")
ERR(err_recursion_limit, "Recursion limit reached.")
ERR(err_cant_be_main_file, "This file may not be used as the main file.%s")
ERR(err_no_labels_here, "Can't use non-static labels here.")
ERR(err_invalid_freespace_request, "Invalid freespace request.")
ERR(err_static_freespace_autoclean, "A static freespace must be targeted by at least one autoclean.")
ERR(err_static_freespace_growing, "A static freespace may not grow.")
ERR(err_no_freespace_in_mapped_banks, "No freespace found in the mapped banks. (Requested size: %s)")
ERR(err_no_freespace, "No freespace found. (Requested size: %s)")
ERR(err_prot_not_at_freespace_start, "PROT must be used at the start of a freespace block.")
ERR(err_prot_too_many_entries, "Too many entries to PROT.")
ERR(err_autoclean_in_freespace, "autoclean used in freespace.")
ERR(err_autoclean_label_at_freespace_end, "Don't autoclean a label at the end of a freespace block, you'll remove some stuff you're not supposed to remove.")
ERR(err_broken_autoclean, "Broken autoclean command.")
ERR(err_pulltable_without_table, "Using pulltable when there is no table on the stack yet.")
ERR(err_pad_in_freespace, "pad does not make sense in a freespaced code.")
//ERR(err_base_label_invalid, "base Label is not valid.")
ERR(err_pushpc_without_pullpc, "pushpc without matching pullpc.")
ERR(err_pullpc_without_pushpc, "pullpc without matching pushpc.")
ERR(err_pullpc_different_arch, "pullpc in another architecture than the pushpc.")
ERR(err_pullbase_without_pushbase, "pullbase without matching pushbase.")
ERR(err_invalid_check, "Invalid check command.")
ERR(err_assertion_failed, "Assertion failed%s")
ERR(err_error_command, "error command%s")
//ERR(err_invalid_print_function_syntax, "Invalid printable string syntax.")
ERR(err_unknown_variable, "Unknown variable.")
ERR(err_pushwarnings_without_pullwarnings, "warnings push without matching warnings pull.")
ERR(err_pullwarnings_without_pushwarnings, "warnings pull without matching warnings push.")
ERR(err_failed_to_open_file_access_denied, "Failed to open file '%s'. Access denied.")
ERR(err_failed_to_open_not_regular_file, "Failed to open file '%s'. Not a regular file (did you try to use a directory?)")
ERR(err_bad_dp_base, "The dp base should be page aligned (i.e. a multiple of 256), got %s")
ERR(err_bad_dp_optimize, "Bad dp optimize value %s, expected: [none, ram, always]")
ERR(err_bad_address_optimize, "Bad dp optimize value %s, expected: [default, ram, mirrors]")
ERR(err_bad_optimize, "Bad optimize value %s, expected: [dp, address]")
//ERR(err_require_parameter, "Missing required function parameter")
//ERR(err_expected_parameter, "Not enough parameters in calling of function %s")
//ERR(err_unexpected_parameter, "Too many parameters in calling of function %s")
ERR(err_duplicate_param_name, "Duplicated parameter name: %s in creation of function %s")
ERR(err_invalid_alignment, "Invalid alignment. Expected a power of 2.")
ERR(err_alignment_too_big, "Requested alignment too large.")
ERR(err_negative_shift, "Bitshift amount is negative.")
ERR(err_macro_not_varadic, "Invalid use of %s, active macro is not variadic.")
ERR(err_vararg_sizeof_nomacro, "Invalid use of sizeof(...), no active macro.")
ERR(err_macro_wrong_min_params, "Variadic macro call with too few parameters")
ERR(err_vararg_out_of_bounds, "Variadic macro parameter %s is out of bounds.%s")
ERR(err_vararg_must_be_last, "Variadic macro parameter must be the last parameter.")
ERR(err_invalid_global_label, "Global label definition contains an invalid label [%s].")
ERR(err_spc700_addr_out_of_range, "Address %s out of range for instruction, valid range is 0000-1FFF")
ERR(err_label_ambiguous, "Label (%s) location is ambiguous due to straddling optimization border.")
ERR(err_feature_unavaliable_in_spcblock, "This feature may not be used while an spcblock is active")
ERR(err_endspcblock_without_spcblock, "Use of endspcblock without matching spcblock")
ERR(err_missing_endspcblock, "Use of endspcblock without matching spcblock")
ERR(err_spcblock_inside_struct, "Can not start an spcblock while a struct is still open")
ERR(err_spcblock_too_few_args, "Too few args passed to spcblock")
ERR(err_spcblock_too_many_args, "Too many args passed to spcblock")
ERR(err_unknown_spcblock_type, "Unknown spcblock format")
ERR(err_custom_spcblock_missing_macro, "Custom spcblock types must refer to a valid macro")
ERR(err_spcblock_macro_doesnt_exist, "Macro specified to custom spcblock was not found")
ERR(err_extra_spcblock_arg_for_type, "Only custom spcblock type takes a fourth argument")
ERR(err_spcblock_macro_must_be_varadic, "Custom spcblock macros must be variadic")
ERR(err_spcblock_macro_invalid_static_args, "Custom spcblock macros must have three static arguments")
ERR(err_spcblock_custom_types_incomplete, "Custom spcblock types are not yet supported. One day.")
ERR(err_invalid_endspcblock_arg, "Invalid argument to endspcblock: \"%s\"")
ERR(err_unknown_endspcblock_format, "Unsupported endspcblock format. Currently supported formats are \"endspcblock\" and \"endspcblock execute [label]\"")
ERR(err_internal_error, "An internal error occured (%s). This is a bug in Asar, please report it at https://github.com/RPGHacker/asar/issues, along with a patch that reproduces it if possible.")
ERR(err_pushns_without_pullns, "pushns without matching pullns.")
ERR(err_pullns_without_pushns, "pullns without matching pushns.")
ERR(err_label_forward, "The use of forward labels is not allowed in this context.")
ERR(err_undefined_char, "'%s' is not defined in the character table")
ERR(err_invalid_utf8, "Invalid text encoding detected. Asar expects UTF-8-encoded text. Please re-save this file in a text editor of choice using UTF-8 encoding.")
ERR(err_cmdl_utf16_to_utf8_failed, "UTF-16 to UTF-8 string conversion failed: %s.")
ERR(err_broken_command, "Broken %s command. %s")
ERR(err_oob, "Operation out of bounds: Requested index %d for object of size %d")
ERR(err_unclosed_vararg, "Variadic macro parameter wasn't closed properly.")
//ERR(err_invalid_vararg, "Trying to use variadic macro parameter syntax to resolve a non variadic argument <%s>.")
ERR(err_invalid_depth_resolve, "Invalid %s resolution depth: Trying to backwards-resolve a %s using %i '^', but current scope only supports up to %i '^'.")
ERR(err_platform_paths, "Platform-specific paths aren'supported. Please use platform-independent paths (use / instead of \\).")
ERR(err_bad_single_line_for, "Single-line for loop not allowed here.")
ERR(err_broken_for_loop, "Broken for loop command: %s")
ERR(err_missing_org, "Missing org or freespace command.")
ERR(err_unclosed_block_comment, "Unclosed block comment.")
ERR(err_bad_addr_mode, "This addressing mode is not valid for this instruction.")
ERR(err_bad_access_width, "This addressing mode can accept %s arguments, but the provided argument is %d-bit.")
ERR(err_label_before_if, "Labels are not allowed before \"%s\" commands. Suggestion: move the label to a separate line.")
ERR(err_bad_type, "Type error when evaluating math: expected %s, got %s")
ERR(err_argument_count, "Wrong number of arguments. Expected %d, got %d")

#undef ERR
