# due to mdbook limitations, we need to provide everything highlight-related in a single file.
# but we still want to keep our Asar syntax highlighter separate for easy updating.

open("theme/highlight.js", 'w').write(
    "/* Autogenerated, do not edit! */" +
    open("./highlight.min.js").read() + "\n" +
    open("./hljs-asar.js").read()
)
